# 定义构建流程
name: Build Process
 
# 当代码被推送到存储库时触发工作流
on: push
 
jobs:
  # 定义构建作业
  build:
    # 在 Windows 环境中运行
    runs-on: windows-2019
 
    steps:
      # 步骤：检出代码
      - name: Checkout code
        uses: actions/checkout@v4
 
      # 步骤：设置 MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
 
      # 步骤：构建 VS 项目
      - name: Build VS Project
        run: |
          # 运行生成 DLL 的命令
          msbuild GB28181_Stress_Tools.sln /p:Configuration=Release /p:Platform=x64
      - name: Deploy
        shell: pwsh
        run: |
          dir
          dir x64
          dir x64\Release
          Compress-Archive -Path .\x64\Release\* GB28181_Stress_Tools.zip
      - uses: actions/upload-artifact@v4
        with:
          name: GB28181_Stress_Tools.zip
          path: GB28181_Stress_Tools.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: GB28181_Stress_Tools.zip
          token: ${{ secrets.GITHUB_TOKEN }}
