# 定义构建流程
name: Build Process
 
# 当代码被推送到存储库时触发工作流
on: push
permissions:
  contents: write

jobs:
  # 定义构建作业
  build:
    # 在 Windows 环境中运行
    runs-on: windows-2019
 
    steps:
      # 步骤：检出代码
      - name: Checkout code
        uses: actions/checkout@v4
 
      # 步骤：设置 MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Set Chinese Locale
        run: |
          chcp 936
          echo 中文环境设置完成 
      - name: Set UI Locale to Chinese
        run: |
          reg add "HKCU\Control Panel\International" /v Locale /t REG_SZ /d 00000804 /f
          reg add "HKCU\Control Panel\Desktop" /v PreferredUILanguages /t REG_MULTI_SZ /d zh-CN /f
          reg add "HKCU\Control Panel\International\User Profile" /v Languages /t REG_MULTI_SZ /d zh-CN /f
          reg add "HKCU\Control Panel\International\User Profile" /v ShowAutoLangOptIn /t REG_DWORD /d 0 /f
          reg add "HKCU\Control Panel\International\User Profile" /v HttpAcceptLanguageOptOut /t REG_DWORD /d 1 /f
      # 步骤：构建 VS 项目
      - name: Build VS Project
        run: |
          # 运行生成 DLL 的命令
          chcp 936
          msbuild GB28181_Stress_Tools.sln /p:Configuration=Release /p:Platform=x64
      - name: Deploy
        shell: pwsh
        run: |
          dir
          dir x64
          dir x64\Release
          Compress-Archive -Path .\x64\Release\* GB28181_Stress_Tools.zip
          dir
          dir x64\Release

      - uses: actions/upload-artifact@v4
        with:
          name: GB28181_Stress_Tools.zip
          path: GB28181_Stress_Tools.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: GB28181_Stress_Tools.zip
          token: ${{ secrets.GITHUB_TOKEN }}
